name: klr
description: A color palette helper.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter        
  fbf:
    path: ../packages/fbf
  archive: ^2.0.13
  charts_painter: ^1.0.0
  color_thief_flutter: ^1.0.2
  csv: ^4.1.0
  file_picker: ^2.1.6
  flutter_colorpicker: ^0.3.5
  flutter_highlight: ^0.6.0
  flutter_sticky_header: ^0.5.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  intl: ^0.17.0
  kdtree: ^0.1.0
  line_awesome_flutter: ^1.0.1
  modal_bottom_sheet: ^2.0.0
  numberpicker: ^2.0.0
  provider: ^4.3.3
  url_launcher: ^5.7.10
  uuid: ^2.2.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # integration_test:
  #   sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: BodoniModa
      fonts:
        - asset: fonts/BodoniModa-ExtraBold.ttf
          weight: 800
        - asset: fonts/BodoniModa-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/BodoniModa-Black.ttf
          weight: 900
        - asset: fonts/BodoniModa-BlackItalic.ttf
          weight: 900
          style: italic
    - family: BeVietnam
      fonts:
        - asset: fonts/BeVietnam-Thin.ttf
          weight: 100
        - asset: fonts/BeVietnam-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/BeVietnam-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/BeVietnam-Italic.ttf
          style: italic
        - asset: fonts/BeVietnam-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/BeVietnam-SemiBold.ttf
          weight: 600
        - asset: fonts/BeVietnam-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/BeVietnam-ExtraBold.ttf
          weight: 800
        - asset: fonts/BeVietnam-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: SpaceMono
      fonts:
        - asset: fonts/SpaceMono-Regular.ttf
        - asset: fonts/SpaceMono-Italic.ttf
          style: italic
        - asset: fonts/SpaceMono-Bold.ttf
          weight: 700
        - asset: fonts/SpaceMono-BoldItalic.ttf
          style: italic
          weight: 700

  assets:
    - images/fivebyfive.png
    - images/logo.png
    - images/logo_e.png
    - images/logo_eb.png
    - images/logo_ebb.png
    - data/colornames.csv

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
